on: [push]

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@master

         - uses: docker/docker-login@v1
           with:
              username: ${{ secrets.REGISTRY_USERNAME }}
              password: ${{ secrets.REGISTRY_PASSWORD }}

         - run: |
              docker build . -t manjudhub/k8sdemo:${{ github.sha }}
              docker push manjudhub/k8sdemo:${{ github.sha }}

         - uses: azure/setup-kubectl@v2.0

         # Set the target AKS cluster.
         - uses: Azure/aks-set-context@v1
           with:
              creds: '${{ secrets.AZURE_CREDENTIALS }}'
              cluster-name: task-1
              resource-group: task

         - uses: Azure/k8s-create-secret@v1.1
           with:
              container-registry-url: hub.docker.com
              container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
              container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
              secret-name: demo-k8s-secret

         - uses: Azure/k8s-deploy@v3.1
           with:
              action: deploy
              manifests: |
                 manifests/deployment.yml
                 #manifests/service.yml
              images: |
                 manjudhub/k8sdemo:${{ github.sha }}
              imagepullsecrets: |
                 demo-k8s-secret
